<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hellocode_potema_branches"
 *
 * Auto generated by Extension Builder 2018-05-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'POTEMA Service Provider',
    'description' => 'Address List of all POTEMA service provider',
    'category' => 'plugin',
    'author' => 'Stefan Sajok',
    'author_email' => 'stefansajok@hotmail.com',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '4.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
